services:
  server:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    networks:
      - network_for_test
    ports:
      - 8080:8080

  test:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    depends_on:
      - server
    networks:
      - network_for_test
    environment:
      - ORIGIN=http://server:8080

networks:
  network_for_test:
    driver: bridge
