name: test

on: push

jobs:
  test:
    name: Run E2E Test on Docker Containers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Run E2E Test on Docker Containers through Docker Network
        run: docker compose up server -d && docker compose up test
